# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageexport.ui'
#
# Created: Thu Oct  1 14:53:37 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ImageExport(object):
    def setupUi(self, ImageExport):
        ImageExport.setObjectName("ImageExport")
        ImageExport.setWindowModality(QtCore.Qt.NonModal)
        ImageExport.setEnabled(True)
        ImageExport.resize(356, 386)
        ImageExport.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        ImageExport.setSizeGripEnabled(True)
        self.buttonBox = QtGui.QDialogButtonBox(ImageExport)
        self.buttonBox.setGeometry(QtCore.QRect(5, 345, 334, 32))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonBox.setFont(font)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtGui.QGroupBox(ImageExport)
        self.groupBox.setGeometry(QtCore.QRect(19, 6, 313, 154))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.image_output_path = QtGui.QLineEdit(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.image_output_path.setFont(font)
        self.image_output_path.setObjectName("image_output_path")
        self.gridLayout.addWidget(self.image_output_path, 0, 0, 1, 2)
        self.image_output_button = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.image_output_button.setFont(font)
        self.image_output_button.setFocusPolicy(QtCore.Qt.TabFocus)
        self.image_output_button.setObjectName("image_output_button")
        self.gridLayout.addWidget(self.image_output_button, 0, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textLabel4_2 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textLabel4_2.setFont(font)
        self.textLabel4_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel4_2.setObjectName("textLabel4_2")
        self.horizontalLayout.addWidget(self.textLabel4_2)
        self.resolution = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resolution.sizePolicy().hasHeightForWidth())
        self.resolution.setSizePolicy(sizePolicy)
        self.resolution.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.resolution.setFont(font)
        self.resolution.setAutoFillBackground(False)
        self.resolution.setObjectName("resolution")
        self.horizontalLayout.addWidget(self.resolution)
        self.textLabel4_3 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textLabel4_3.setFont(font)
        self.textLabel4_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.textLabel4_3.setObjectName("textLabel4_3")
        self.horizontalLayout.addWidget(self.textLabel4_3)
        self.textLabel4 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textLabel4.setFont(font)
        self.textLabel4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.textLabel4.setObjectName("textLabel4")
        self.horizontalLayout.addWidget(self.textLabel4)
        self.format = QtGui.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.format.setFont(font)
        self.format.setObjectName("format")
        self.format.addItem(QtCore.QString())
        self.format.addItem(QtCore.QString())
        self.format.addItem(QtCore.QString())
        self.format.addItem(QtCore.QString())
        self.format.addItem(QtCore.QString())
        self.horizontalLayout.addWidget(self.format)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        self.tmp_render = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tmp_render.setFont(font)
        self.tmp_render.setObjectName("tmp_render")
        self.gridLayout.addWidget(self.tmp_render, 2, 0, 1, 1)
        self.auto_open = QtGui.QCheckBox(self.groupBox)
        self.auto_open.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.auto_open.setFont(font)
        self.auto_open.setObjectName("auto_open")
        self.gridLayout.addWidget(self.auto_open, 2, 1, 1, 2)
        self.transparent_background = QtGui.QCheckBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.transparent_background.setFont(font)
        self.transparent_background.setObjectName("transparent_background")
        self.gridLayout.addWidget(self.transparent_background, 3, 0, 1, 3)
        self.grpMap = QtGui.QGroupBox(ImageExport)
        self.grpMap.setGeometry(QtCore.QRect(20, 175, 316, 156))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grpMap.sizePolicy().hasHeightForWidth())
        self.grpMap.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.grpMap.setFont(font)
        self.grpMap.setObjectName("grpMap")
        self.gridLayout_2 = QtGui.QGridLayout(self.grpMap)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(self.grpMap)
        self.label.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.sizes = QtGui.QComboBox(self.grpMap)
        self.sizes.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sizes.setFont(font)
        self.sizes.setObjectName("sizes")
        self.gridLayout_2.addWidget(self.sizes, 0, 1, 1, 2)
        self.neatline = QtGui.QCheckBox(self.grpMap)
        self.neatline.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.neatline.setFont(font)
        self.neatline.setObjectName("neatline")
        self.gridLayout_2.addWidget(self.neatline, 1, 0, 1, 2)
        self.comboBox = QtGui.QComboBox(self.grpMap)
        self.comboBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem(QtCore.QString())
        self.comboBox.addItem(QtCore.QString())
        self.gridLayout_2.addWidget(self.comboBox, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.grpMap)
        self.label_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 2)
        self.fontComboBox = QtGui.QFontComboBox(self.grpMap)
        self.fontComboBox.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fontComboBox.setFont(font)
        self.fontComboBox.setObjectName("fontComboBox")
        self.gridLayout_2.addWidget(self.fontComboBox, 3, 0, 1, 3)
        self.textLabel4_2.setBuddy(self.format)
        self.textLabel4_3.setBuddy(self.format)
        self.textLabel4.setBuddy(self.format)

        self.retranslateUi(ImageExport)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), ImageExport.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), ImageExport.reject)
        QtCore.QMetaObject.connectSlotsByName(ImageExport)

    def retranslateUi(self, ImageExport):
        ImageExport.setWindowTitle(QtGui.QApplication.translate("ImageExport", "Quantumnik - Image Export", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ImageExport", "Image Output", None, QtGui.QApplication.UnicodeUTF8))
        self.image_output_path.setToolTip(QtGui.QApplication.translate("ImageExport", "Name for the map file to be created from the QGIS project file", None, QtGui.QApplication.UnicodeUTF8))
        self.image_output_button.setText(QtGui.QApplication.translate("ImageExport", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4_2.setText(QtGui.QApplication.translate("ImageExport", "Resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4_3.setText(QtGui.QApplication.translate("ImageExport", "(ppi)", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel4.setText(QtGui.QApplication.translate("ImageExport", "Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.format.setItemText(0, QtGui.QApplication.translate("ImageExport", "png", None, QtGui.QApplication.UnicodeUTF8))
        self.format.setItemText(1, QtGui.QApplication.translate("ImageExport", "jpeg", None, QtGui.QApplication.UnicodeUTF8))
        self.format.setItemText(2, QtGui.QApplication.translate("ImageExport", "pdf", None, QtGui.QApplication.UnicodeUTF8))
        self.format.setItemText(3, QtGui.QApplication.translate("ImageExport", "svg", None, QtGui.QApplication.UnicodeUTF8))
        self.format.setItemText(4, QtGui.QApplication.translate("ImageExport", "ps", None, QtGui.QApplication.UnicodeUTF8))
        self.tmp_render.setText(QtGui.QApplication.translate("ImageExport", "Render to tmp file...", None, QtGui.QApplication.UnicodeUTF8))
        self.auto_open.setText(QtGui.QApplication.translate("ImageExport", "Open after save...", None, QtGui.QApplication.UnicodeUTF8))
        self.transparent_background.setText(QtGui.QApplication.translate("ImageExport", "Transparent Background", None, QtGui.QApplication.UnicodeUTF8))
        self.grpMap.setTitle(QtGui.QApplication.translate("ImageExport", "Print Options (Not Yet Enabled)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ImageExport", "Custom Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.neatline.setText(QtGui.QApplication.translate("ImageExport", "Draw Neatline", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("ImageExport", "Landscape", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("ImageExport", "Portrait", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ImageExport", "Text Override:", None, QtGui.QApplication.UnicodeUTF8))

